In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#sns.set()
mydata=pd.read_csv("customer_churn.csv")
mydata.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
mydata.columns= mydata.columns.str.lower()

In [ ]:
mydata.head()

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df=mydata.iloc[:,3:]

In [ ]:
df.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
y=df.iloc[:,-1]
y.head()

0    1
1    0
2    1
3    0
4    0
Name: exited, dtype: int64

In [ ]:
X= df.drop(['exited'],axis=1)

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: exited, dtype: int64

In [ ]:
X.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [ ]:
X.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [ ]:
X=pd.get_dummies(X,drop_first=True)

In [ ]:
X.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,geography_Germany,geography_Spain,gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33, random_state=432)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_train=pd.DataFrame(X_train,columns=X_test.columns)

X_test=sc.transform(X_test)
X_test=pd.DataFrame(X_test,columns=X_train.columns)

In [ ]:
len(y)

In [ ]:
y.value_counts()

In [ ]:
7963/(7963+2037)

In [ ]:
y.value_counts().head(1)/len(y)

# Null Accuracy

In [ ]:
y.value_counts().head(1)/len(y)

In [ ]:
len(y)

In [ ]:
y.value_counts().head(1)/len(y)

In [ ]:
null_accuracy=y.value_counts().head(1)/len(y)

In [ ]:
print(null_accuracy)

In [ ]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(X_train,y_train)
y_pred= model.predict(X_test)

In [ ]:
#from sklearn.ensemble import RandomForestClassifier
#model1=RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

In [ ]:
#y_pred= model.predict(X_test)

In [ ]:
#y_pred

In [ ]:
#y_pred_prob= model.predict_proba(X_test)

In [ ]:
#y_pred_prob

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm= confusion_matrix(y_test,y_pred)

In [ ]:
cm

In [ ]:
TN=cm[0,0]
TN

In [ ]:
TP= cm[1,1]
TP

In [ ]:
FP= cm[0,1]
FP

In [ ]:
FN=cm[1,0]
FN

In [1]:
Sensitivity = TP/(TP+FN)
Sensitivity

NameError: ignored

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(y_test,y_pred)

In [ ]:
##True Negative
TN=cm[0,0]
##False Negative
FN=cm[1,0]
##False Positives
FP=cm[0,1]
##True Positives
TP=cm[1,1]

In [ ]:
print(TN)
print(FN)
print(FP)
print(TP)

### Sensitivity

In [ ]:
## Calculating Sensitivity
Sensitivity=TP/(TP+FN)
Sensitivity

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

### Specificity

In [ ]:
##Calculating Specificity
Specificity=TN/(TN+FP)
Specificity

### Precision

In [ ]:
##Precision
Precision= TP/(TP+FP)
Precision

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred)

### False Positive Rate

In [ ]:
##Calculate False Positive_rate
False_Positive_rate= FP/(FP+TN)
False_Positive_rate

In [ ]:
1- Specificity

### F1 Score : Harmonic mean of Sensitivity and Precision

In [ ]:
(2 *(Sensitivity * Precision))/(Sensitivity+Precision)

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1_score(y_test,y_pred)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred))

In [ ]:
print(y_pred)

In [ ]:
y_pred[:20]

In [ ]:
y_pred_prob= model.predict_proba(X_test)

In [ ]:
y_pred_prob[:20]

In [ ]:
y_pred_prob= model.predict_proba(X_test)

In [ ]:
y_pred_prob[:20]

In [ ]:
model.predict_proba(X_test)[:10]

In [ ]:
model.predict(X_test)[:10]

In [ ]:
y_pred_prob=model.predict_proba(X_test)[:,1]

In [ ]:
y_pred_prob

In [ ]:
y_pred= (y_pred_prob>0.3)

In [ ]:
y_pred[:10]

In [ ]:
y_pred_prob=model.predict_proba(X_test)[:,1]

In [ ]:
y_pred_prob[:15]>0.5

In [ ]:
y_pred_prob

In [ ]:
import seaborn as sns
sns.set()

In [ ]:
plt.hist(y_pred_prob);

In [ ]:
plt.hist(y_pred_prob);

In [ ]:
plt.hist(y_pred_prob);

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
#histogram of class distribution
plt.hist(y_pred_prob,color='r')
plt.title("Histogram of Predicted Probabilities")
plt.xlabel("Predicted Probabilities of Customer Churn")
plt.ylabel("Frequency")
plt.show()

In [ ]:
plt.hist(y_pred_prob,color='r');

In [ ]:
y_pred_prob[:20]

In [ ]:
y_pred[:20]

In [ ]:
plt.hist(y_pred_prob);

In [ ]:

y_pred_prob=model.predict_proba(X_test)[:,1]

In [ ]:
y_pred_prob

In [ ]:
plt.hist(y_pred_prob);

In [ ]:
plt.hist(y_pred_prob,color='r');

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
#histogram of class distribution
plt.hist(y_pred_prob,color='r')
plt.title("Histogram of Predicted Probabilities")
plt.xlabel("Predicted Probabilities of Customer Churn")
plt.ylabel("Frequency")
plt.show()

# ROC and AUC Start from here

In [ ]:
from sklearn.metrics import  roc_auc_score ,roc_curve

In [ ]:
roc_curve(y_test,y_pred_prob)

In [ ]:
fpr,tpr,thresholds= roc_curve(y_test,y_pred_prob)

In [ ]:
plt.plot(fpr,tpr);

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score

fpr,tpr,thresholds =roc_curve(y_test,y_pred_prob)

In [ ]:
plt.plot(fpr,tpr);

In [ ]:
roc_auc_score(y_test,y_pred_prob)

In [ ]:
from sklearn.metrics import roc_curve

fpr,tpr,thresholds=roc_curve(y_test,y_pred_prob)

In [ ]:
from sklearn.metrics import roc_curve
fpr,tpr,thresholds=roc_curve(y_test,y_pred_prob)

In [ ]:
from sklearn.metrics import roc_curve
fpr,tpr,thresholds = roc_curve(y_test,y_pred_prob)

In [ ]:
plt.plot(fpr,tpr);

In [ ]:
import matplotlib.pyplot as plt
plt.plot(fpr,tpr)
plt.title("ROC Curve for the Problem")
plt.xlabel("False Positive rate (1-Specificity)")
plt.ylabel("True Positive rate (Sensitivity)")
plt.grid(True)
plt.show()

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred_prob)

In [ ]:
from sklearn.metrics import roc_auc_score
auc=roc_auc_score(y_test,y_pred_prob)
print(auc)

In [ ]:
import matplotlib.pyplot as plt
plt.plot(fpr,tpr)
plt.title("ROC Curve for the Problem")
plt.xlabel("False Positive rate (1-Specificity)")
plt.ylabel("True Positive rate (Sensitivity)")
plt.grid(True)
plt.show()

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred_prob)

# Skip it for today !

In [ ]:
def optimum_threshold(my_threshold):
    print ("Sensitivity:",tpr[thresholds>my_threshold][-1])
    print ("FPR:",fpr[thresholds>my_threshold][-1])

In [ ]:
optimum_threshold(0)

In [ ]:
optimum_threshold(1)

In [ ]:
optimum_threshold(0.1)

In [ ]:
False_Positive_rate

In [ ]:
optimum_threshold(0.1)

In [ ]:
optimum_threshold(0)

In [ ]:
optimum_threshold(0.4)

In [ ]:
optimum_threshold(0)

In [ ]:
optimum_threshold(0)

In [ ]:
optimum_threshold(0.1)

In [ ]:
optimum_threshold(0.2)

In [ ]:
optimum_threshold(0.5)

In [ ]:
optimum_threshold(0.15)

In [ ]:
optimum_threshold(0.3)

In [ ]:
optimum_threshold(0.32)

In [ ]:
y_pred , y_pred_prob

In [ ]:
y_pred_prob

In [ ]:
first_6=y_pred_prob[:6]

In [ ]:
first_6

In [ ]:
first_6>0.2

In [ ]:
y_pred= y_pred_prob>0.4

In [ ]:
y_pred= y_pred_prob>0.3

In [ ]:
y_pred_prob

In [ ]:
y_pred